#!/bin/bash

if [ -e /usr/bin/ld.yh ];then
echo "exist!"
exit
else
echo "now rename"
sudo mv   /usr/bin/gcc /usr/bin/gcc.yh
sudo mv   /usr/bin/g++ /usr/bin/g++.yh
sudo mv  /usr/bin/ld	/usr/bin/ld.yh
fi

