#!/bin/bash

if [ -e /usr/bin/ld.yh ];then
echo "exist!"
exit
else
echo "now copy"
sudo cp -f  /usr/bin/gcc /usr/bin/gcc.yh
sudo cp -f  /usr/bin/g++ /usr/bin/g++.yh
sudo cp -f /usr/bin/ld	/usr/bin/ld.yh
fi

